# Generated by Django 5.0.2 on 2024-02-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blog_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=2000)),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listBlog.blog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("content_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=2000)),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listBlog.blog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageUrl",
            fields=[
                ("image_url_id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField()),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listBlog.blog"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                ("title_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "blog_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listBlog.blog"
                    ),
                ),
            ],
        ),
    ]
